CROP RECOMMENDATION PROJECT -WEEK 1

In [ ]:
#IMPORTING NECCESSARY LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#INSTALLING PACKAGE
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 2.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/11.5 MB 3.2 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/11.5 MB 3.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/11.5 MB 2.7 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.5 MB 2.8 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/11.5 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.4/11.5 MB 2.3 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.5 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.9/11.5 MB 2.1 MB/s eta 0:00:04
   --------------- ------------------------ 4.5/11.5 MB 2.1 MB/s eta 0:00:04
   ----------------- ---------------------- 5.0/11.5 MB 2.1 MB/s eta 0:00:04
   ------------------ --------------------- 5.2/11.5 MB 2.1 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.5 MB 2.1 MB/s eta 0:00:03
   --------------------- ------------------ 6.3/11.5 MB 2.1 MB/s eta 0:00:03
   ----------------------- ---------------- 6.8/11.5 MB 2.1 MB/s eta 0:00:03
   ------------------------ --------------- 7.1/11.5 MB 2.1 MB/s eta 0:00:03
   ------------------------- -------------- 7.3/11.5 MB 2.1 MB/s eta 0:00:03
   --------------------------- ------------ 7.9/11.5 MB 2.0 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.5 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 8.9/11.5 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 9.4/11.5 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.5 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 2.1 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2025.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.1-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.55.6-cp313-cp313-win_amd64.whl.metadata (169 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.0 MB 2.8 MB/s eta 0:00:03
   --------- ------------------------------ 1.8/8.0 MB 3.2 MB/s eta 0:00:02
   ------------- -------------------------- 2.6/8.0 MB 3.6 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.0 MB 3.6 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.0 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.0 MB 3.4 MB/s eta 0:00:01
   -------------------------- ------------- 5.2/8.0 MB 3.2 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.0 MB 3.1 MB/s eta 0:00:01
   ------------------------------ --------- 6.0/8.0 MB 2.9 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 2.5 MB/s eta 0:00:00
Downloading contourpy-1.3.1-cp313-cp313-win_amd64.whl (220 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.55.6-cp313-cp313-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.2 MB 1.8 MB/s eta 0:00:01
   ----------------------- ---------------- 1.3/2.2 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 2.6 MB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 1.7 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl (71 kB)
Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.6 MB 3.7 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.6 MB 3.8 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.6 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 2.4/2.6 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.6 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.6 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 1.8 MB/s eta 0:00:00
Downloading pyparsing-3.2.1-py3-none-any.whl (107 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.1 cycler-0.12.1 fonttools-4.55.6 kiwisolver-1.4.8 matplotlib-3.10.0 pillow-11.1.0 pyparsing-3.2.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.2.0)
Requirement already satisfied: pandas>=1.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.6)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#LOADING DATASET
crop=pd.read_csv("Crop_recommendation.csv")

In [11]:

crop.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [12]:
crop.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [14]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [16]:
#CHECK NULL VALUES
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [20]:
crop.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [22]:
#CHECK TARGET FEATURE DISTRIBUTION
crop['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64